name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./giftlink-backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js (v22.17.0)
        uses: actions/setup-node@v3
        with:
          node-version: '22.17.0'

      - name: Install JSHint
        run: npm install jshint --save-dev

      - name: Run JSHint with config
        run: |
          jshint --config .jshintrc app.js routes/*.js
          echo "✓ Backend linting completed"

  build_frontend:
    name: Build Frontend
    needs: lint_backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./giftlink-frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: |
          npx eslint . --ext .js,.jsx --fix
          npx eslint . --ext .js,.jsx --format junit --output-file eslint-results.xml || true

      - name: Build React App
        run: npm run build